#!/usr/bin/env python3
"""Generate a filled A2P 10DLC answer sheet from the skill templates.

Scans templates/*.md for {{placeholder}} tokens, asks you for each value once,
substitutes everywhere, and writes my-a2p-answers.md - a single copy-paste sheet
for the Twilio Console.

Stdlib only. No installs. Run from the skill directory:

    python3 generate_answers.py
"""

import re
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent
TEMPLATE_DIR = SKILL_DIR / "templates"
OUTPUT = SKILL_DIR / "my-a2p-answers.md"

# Order the answer sheet to mirror the Twilio Console flow.
TEMPLATE_ORDER = [
    "campaign-description.md",
    "sample-messages.md",
    "consent-flow.md",
    "keywords-and-autoreplies.md",
    "privacy-policy-clause.md",
]

TOKEN_RE = re.compile(r"\{\{([^}]+)\}\}")

# Meta-tokens that appear in the templates' instructional prose
# (e.g. "Replace every {{placeholder}}.") and must never be treated as
# a fillable field.
RESERVED_TOKENS = {"placeholder"}


def label_for(token: str) -> str:
    """Turn a raw token (maybe with an 'e.g.' hint) into a clean prompt."""
    return token.strip()


def collect_tokens(texts):
    """Return unique tokens in first-seen order across all template texts."""
    seen = {}
    for text in texts:
        for match in TOKEN_RE.finditer(text):
            raw = match.group(1).strip()
            if raw in RESERVED_TOKENS:
                continue
            if raw not in seen:
                seen[raw] = label_for(raw)
    return list(seen.items())


def main():
    if not TEMPLATE_DIR.is_dir():
        sys.exit(f"templates/ not found at {TEMPLATE_DIR}")

    templates = []
    for name in TEMPLATE_ORDER:
        path = TEMPLATE_DIR / name
        if not path.is_file():
            print(f"  (skipping missing template: {name})", file=sys.stderr)
            continue
        templates.append((name, path.read_text(encoding="utf-8")))

    if not templates:
        sys.exit("No templates found to fill.")

    tokens = collect_tokens(text for _, text in templates)

    print("\nA2P 10DLC answer-sheet generator")
    print("=" * 40)
    print(f"Fill {len(tokens)} values once; they apply across every field.")
    print("Press Enter to leave a value as its {{placeholder}} for now.\n")

    answers = {}
    for raw, label in tokens:
        value = input(f"  {label}: ").strip()
        answers[raw] = value if value else "{{" + raw + "}}"

    def substitute(text):
        return TOKEN_RE.sub(lambda m: answers.get(m.group(1).strip(), m.group(0)), text)

    parts = [
        "# My A2P 10DLC Answers",
        "",
        "Generated by generate_answers.py. Copy each block into the Twilio Console.",
        "Re-run pre-submission-checklist.md before you click Create.",
        "",
        "---",
        "",
    ]
    for name, text in templates:
        parts.append(substitute(text))
        parts.append("\n---\n")

    OUTPUT.write_text("\n".join(parts), encoding="utf-8")

    remaining = [raw for raw, v in answers.items() if v.startswith("{{")]
    print(f"\nWrote {OUTPUT}")
    if remaining:
        print(f"Still unfilled ({len(remaining)}): {', '.join(remaining)}")
        print("Edit the file or re-run to fill them.")
    else:
        print("All placeholders filled.")
    print("\nNext: open the file, then walk playbook/one-shot-approval.md.\n")


if __name__ == "__main__":
    try:
        main()
    except (KeyboardInterrupt, EOFError):
        print("\nCancelled.")
        sys.exit(1)
